FREE_ALPHA_VANTAGE_FUNCTIONS = [
    
    # Core Stock Time Series
    "TIME_SERIES_DAILY",
    "TIME_SERIES_WEEKLY",
    "TIME_SERIES_WEEKLY_ADJUSTED",
    "TIME_SERIES_MONTHLY",
    "TIME_SERIES_MONTHLY_ADJUSTED",
    "GLOBAL_QUOTE",
    "SYMBOL_SEARCH",
    "MARKET_STATUS",

    # Forex
    "CURRENCY_EXCHANGE_RATE",
    "FX_DAILY",
    "FX_WEEKLY",
    "FX_MONTHLY",
    "FX_INTRADAY",

    # Cryptocurrency
    "DIGITAL_CURRENCY_DAILY",
    "DIGITAL_CURRENCY_WEEKLY",
    "DIGITAL_CURRENCY_MONTHLY",
    "CRYPTO_RATING",                 # sometimes available
    "CRYPTO_INTRADAY",               # may have limitations

    # Fundamental Data
    "OVERVIEW",
    "INCOME_STATEMENT",
    "BALANCE_SHEET",
    "CASH_FLOW",
    "EARNINGS",
    "EARNINGS_ESTIMATES",
    "DIVIDENDS",
    "SPLITS",
    "SHARES_OUTSTANDING",
    "ETF_PROFILE",
    "LISTING_STATUS",
    "EARNINGS_CALENDAR",
    "IPO_CALENDAR",

    # Commodities
    "WTI",
    "BRENT",
    "NATURAL_GAS",
    "COPPER",
    "ALUMINUM",
    "WHEAT",
    "CORN",
    "COTTON",
    "SUGAR",
    "COFFEE",
    "ALL_COMMODITIES",
    "GOLD",                         
    "SILVER",

    # Economic Indicators
    "REAL_GDP",
    "REAL_GDP_PER_CAPITA",
    "TREASURY_YIELD",
    "FEDERAL_FUNDS_RATE",
    "CPI",
    "INFLATION",
    "RETAIL_SALES",
    "DURABLES",
    "UNEMPLOYMENT",
    "NONFARM_PAYROLL",

    # Technical Indicators (most are free)
    "SMA",
    "EMA",
    "WMA",
    "DEMA",
    "TEMA",
    "TRIMA",
    "KAMA",
    "MAMA",
    "T3",
    "MACDEXT",
    "STOCH",
    "STOCHF",
    "RSI",
    "STOCHRSI",
    "WILLR",
    "ADX",
    "ADXR",
    "APO",
    "PPO",
    "MOM",
    "BOP",
    "CCI",
    "CMO",
    "ROC",
    "ROCR",
    "AROON",
    "AROONOSC",
    "MFI",
    "TRIX",
    "ULTOSC",
    "DX",
    "MINUS_DI",
    "PLUS_DI",
    "MINUS_DM",
    "PLUS_DM",
    "BBANDS",
    "MIDPOINT",
    "MIDPRICE",
    "SAR",
    "TRANGE",
    "ATR",
    "NATR",
    "AD",
    "ADOSC",
    "OBV",
    "HT_TRENDLINE",
    "HT_SINE",
    "HT_TRENDMODE",
    "HT_DCPERIOD",
    "HT_DCPHASE",
    "HT_PHASOR",

    # Alpha Intelligence (partially free)
    "NEWS_SENTIMENT",
    "TOP_GAINERS_LOSERS",
    "INSIDER_TRANSACTIONS",
]