CANONICAL_COLUMNS = [
    "event_id",
    "date",
    "country_iso3",
    "event_type",
    "severity",
    "lat",
    "lon",
    "source",
]

GKG_EVENT_TYPES: dict[str, str] = {
    "PROTEST": "protest",
    "TAX_FNCACT_Protest": "protest",
    "TAX_FNCACT_Riot": "protest",
    "GENERAL_CRISIS_RIOTPROTEST": "protest",
    "SOC_RIOT": "protest",
    "CONFLICT": "conflict",
    "GENERAL_CONFLICT": "conflict",
    "MAR_EVENT_MILITARY": "conflict",
    "TAX_FNCACT_Assault": "assault",
    "TAX_FNCACT_Fight": "fight",
    "TAX_FNCACT_Threaten": "threaten",
    "TAX_FNCACT_Sanction": "sanction",
    "TAX_FNCACT_Embargo": "sanction",
    "DIPLOMACY": "diplomacy",
    "TAX_FNCACT_Diplomacy": "diplomacy",
    "TAX_FNCACT_Agree": "diplomacy",
    "TAX_FNCACT_Endorse": "diplomacy",
    "TAX_FNCACT_Appeal": "diplomacy",
}

EVENT_THEMES: dict[str, list[str]] = {
    "PROTEST": ["PROTEST", "TAX_FNCACT_Protest", "TAX_FNCACT_Riot", "GENERAL_CRISIS_RIOTPROTEST", "SOC_RIOT"],
    "CONFLICT": ["CONFLICT", "GENERAL_CONFLICT", "MAR_EVENT_MILITARY", "TAX_FNCACT_Assault", "TAX_FNCACT_Fight"],
    "DIPLOMACY": ["DIPLOMACY", "TAX_FNCACT_Diplomacy", "TAX_FNCACT_Agree", "TAX_FNCACT_Endorse"],
    "SANCTIONS": ["TAX_FNCACT_Sanction", "TAX_FNCACT_Embargo"],
    "ASSAULT": ["TAX_FNCACT_Assault"],
    "FIGHT": ["TAX_FNCACT_Fight"],
    "MASS_VIOLENCE": ["TAX_FNCACT_Assault", "TAX_FNCACT_Fight"],
}


GDELT_EVENT_COLUMNS = [
    "GlobalEventID",
    "SQLDATE",
    "MonthYear",
    "Year",
    "FractionDate",
    "Actor1Code",
    "Actor1Name",
    "Actor1CountryCode",
    "Actor1KnownGroupCode",
    "Actor1EthnicCode",
    "Actor1Religion1Code",
    "Actor1Religion2Code",
    "Actor1Type1Code",
    "Actor1Type2Code",
    "Actor1Type3Code",
    "Actor2Code",
    "Actor2Name",
    "Actor2CountryCode",
    "Actor2KnownGroupCode",
    "Actor2EthnicCode",
    "Actor2Religion1Code",
    "Actor2Religion2Code",
    "Actor2Type1Code",
    "Actor2Type2Code",
    "Actor2Type3Code",
    "IsRootEvent",
    "EventCode",
    "EventBaseCode",
    "EventRootCode",
    "QuadClass",
    "GoldsteinScale",
    "NumMentions",
    "NumSources",
    "NumArticles",
    "AvgTone",
    "Actor1Geo_Type",
    "Actor1Geo_FullName",
    "Actor1Geo_CountryCode",
    "Actor1Geo_ADM1Code",
    "Actor1Geo_ADM2Code",
    "Actor1Geo_Lat",
    "Actor1Geo_Long",
    "Actor1Geo_FeatureID",
    "Actor2Geo_Type",
    "Actor2Geo_FullName",
    "Actor2Geo_CountryCode",
    "Actor2Geo_ADM1Code",
    "Actor2Geo_ADM2Code",
    "Actor2Geo_Lat",
    "Actor2Geo_Long",
    "Actor2Geo_FeatureID",
    "ActionGeo_Type",
    "ActionGeo_FullName",
    "ActionGeo_CountryCode",
    "ActionGeo_ADM1Code",
    "ActionGeo_ADM2Code",
    "ActionGeo_Lat",
    "ActionGeo_Long",
    "ActionGeo_FeatureID",
    "DATEADDED",
    "SOURCEURL",
]

GDELT_DOC_API = "https://api.gdeltproject.org/api/v2/doc/doc"
GDELT_MASTER = "http://data.gdeltproject.org/gdeltv2/masterfilelist.txt"
