class ParserEngine:

    def detect_format(self, source: object) -> str:
        ...

    def parse(self, raw_data: object, format: str | None = None) -> object:
        ...

    def parse_csv(self, raw_data: object) -> object:
        ...

    def parse_json(self, raw_data: object) -> object:
        ...

    def parse_parquet(self, raw_data: object) -> object:
        ...

    def parse_xml(self, raw_data: object) -> object:
        ...
